export const carousel = [
  {
    index: 1, 
    id: 1,
    img: '/assets/images/scHome.png',
    alt: 'Home Page',
  },
  {
    index: 1, 
    id: 2,
    img: '/assets/images/scAboutUs.png',
    alt: 'About Page',
  },
  {
    index: 1, 
    id: 3,
    img: '/assets/images/scMeet.png',
    alt: 'Officer Page',
  },
  {
    index: 1, 
    id: 4,
    img: '/assets/images/scFAQ.png',
    alt: 'FAQ Page',
  },
  {
    index: 1, 
    id: 5,
    img: '/assets/images/scJoin.png',
    alt: 'Join Page',
  },
  {
    index: 1, 
    id: 6,
    img: '/assets/images/scEvents.png',
    alt: 'Events Page',
  },
  {
    index: 1, 
    id: 7,
    img: '/assets/images/scContact.png',
    alt: 'Contact Page',
  },
  {
    index: 2, 
    id: 5,
    img: '/assets/images/scHome.png',
    alt: '',
  },
  {
    index: 2, 
    id: 6,
    img: '',
    alt: '',
  },
  {
    index: 2, 
    id: 7,
    img: '',
    alt: '',
  },
  {
    index: 2, 
    id: 8,
    img: '',
    alt: '',
  },
  {
    index: 3, 
    id: 9,
    img: '/assets/images/scHomePage.png',
    alt: 'NuCamp Home',
  },
  {
    index: 3, 
    id: 10,
    img: '/assets/images/scFullDirectory.png',
    alt: 'Directory page',
  },
  {
    index: 3, 
    id: 11,
    img: '/assets/images/scDirectory.png',
    alt: 'Directory View',
  },
  {
    index: 3, 
    id: 12,
    img: '/assets/images/scComment.png',
    alt: 'Comment Form',
  },
  {
    index: 3, 
    id: 13,
    img: '/assets/images/scAbout.png',
    alt: 'About Page',
  },
  {
    index: 3, 
    id: 14,
    img: '/assets/images/scContactUs.png',
    alt: 'Contact Page',
  },
  {
    index: 4, 
    id: 13,
    img: '',
    alt: '',
  },
  {
    index: 4, 
    id: 14,
    img: '',
    alt: '',
  },
  {
    index: 4, 
    id: 15,
    img: '',
    alt: '',
  },
  {
    index: 4, 
    id: 16,
    img: '',
    alt: '',
  },
]